# Generated by Django 4.2.14 on 2024-09-25 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_callback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="callback",
            name="material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.material",
            ),
        ),
    ]
