# Generated by Django 4.2.7 on 2024-10-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_pricelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='file',
            field=models.FileField(upload_to='price_lists/', verbose_name='Файл прайс-листа'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название прайс-листа'),
        ),
    ]
