# Generated by Django 4.2.14 on 2024-10-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_pricelist_file_alter_pricelist_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Companies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="companies/")),
            ],
        ),
    ]
