# Generated by Django 4.2.14 on 2024-10-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_companies"),
    ]

    operations = [
        migrations.AddField(
            model_name="companies",
            name="link",
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
