# Generated by Django 4.2.14 on 2024-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_companies_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="desc1",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="desc2",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="material",
            name="desc3",
            field=models.TextField(null=True),
        ),
    ]
