# Generated by Django 4.2.7 on 2024-10-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_material_desc1_material_desc2_material_desc3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='price',
        ),
        migrations.RemoveField(
            model_name='material',
            name='stock',
        ),
    ]
